/*
 * OpenFaaS API Gateway
 * OpenFaaS API documentation
 *
 * OpenAPI spec version: 0.8.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InfoProviderVersion;
import java.io.IOException;

/**
 * The OpenFaaS Provider
 */
@ApiModel(description = "The OpenFaaS Provider")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-06T06:46:10.176+02:00")
public class InfoProvider {
  @SerializedName("provider")
  private String provider = null;

  @SerializedName("orchestration")
  private String orchestration = null;

  @SerializedName("version")
  private InfoProviderVersion version = null;

  public InfoProvider provider(String provider) {
    this.provider = provider;
    return this;
  }

   /**
   * Get provider
   * @return provider
  **/
  @ApiModelProperty(example = "faas-swarm", value = "")
  public String getProvider() {
    return provider;
  }

  public void setProvider(String provider) {
    this.provider = provider;
  }

  public InfoProvider orchestration(String orchestration) {
    this.orchestration = orchestration;
    return this;
  }

   /**
   * Get orchestration
   * @return orchestration
  **/
  @ApiModelProperty(example = "swarm", value = "")
  public String getOrchestration() {
    return orchestration;
  }

  public void setOrchestration(String orchestration) {
    this.orchestration = orchestration;
  }

  public InfoProvider version(InfoProviderVersion version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public InfoProviderVersion getVersion() {
    return version;
  }

  public void setVersion(InfoProviderVersion version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfoProvider infoProvider = (InfoProvider) o;
    return Objects.equals(this.provider, infoProvider.provider) &&
        Objects.equals(this.orchestration, infoProvider.orchestration) &&
        Objects.equals(this.version, infoProvider.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(provider, orchestration, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfoProvider {\n");
    
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    orchestration: ").append(toIndentedString(orchestration)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

