/*
 * OpenFaaS API Gateway
 * OpenFaaS API documentation
 *
 * OpenAPI spec version: 0.8.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DeleteFunctionRequest;
import io.swagger.client.model.FunctionDefintion;
import io.swagger.client.model.FunctionListEntry;
import io.swagger.client.model.Info;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Invoke a function asynchronously in OpenFaaS
     *
     * See https://github.com/openfaas/faas/blob/master/guide/asynchronous.md.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void asyncFunctionFunctionNamePostTest() throws ApiException {
        String functionName = null;
        byte[] input = null;
        api.asyncFunctionFunctionNamePost(functionName, input);

        // TODO: test validations
    }
    
    /**
     * Invoke a function defined in OpenFaaS
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void functionFunctionNamePostTest() throws ApiException {
        String functionName = null;
        byte[] input = null;
        api.functionFunctionNamePost(functionName, input);

        // TODO: test validations
    }
    
    /**
     * Healthcheck
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void healthzGetTest() throws ApiException {
        api.healthzGet();

        // TODO: test validations
    }
    
    /**
     * Event-sink for AlertManager, for auto-scaling
     *
     * Internal use for AlertManager, requires valid AlertManager alert JSON
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemAlertPostTest() throws ApiException {
        Object body = null;
        api.systemAlertPost(body);

        // TODO: test validations
    }
    
    /**
     * Get a summary of an OpenFaaS function
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemFunctionFunctionNameGetTest() throws ApiException {
        String functionName = null;
        FunctionListEntry response = api.systemFunctionFunctionNameGet(functionName);

        // TODO: test validations
    }
    
    /**
     * Remove a deployed function.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemFunctionsDeleteTest() throws ApiException {
        DeleteFunctionRequest body = null;
        api.systemFunctionsDelete(body);

        // TODO: test validations
    }
    
    /**
     * Get a list of deployed functions with: stats and image digest
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemFunctionsGetTest() throws ApiException {
        List<FunctionListEntry> response = api.systemFunctionsGet();

        // TODO: test validations
    }
    
    /**
     * Deploy a new function.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemFunctionsPostTest() throws ApiException {
        FunctionDefintion body = null;
        api.systemFunctionsPost(body);

        // TODO: test validations
    }
    
    /**
     * Update a function.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemFunctionsPutTest() throws ApiException {
        FunctionDefintion body = null;
        api.systemFunctionsPut(body);

        // TODO: test validations
    }
    
    /**
     * Get info such as provider version number and provider orchestrator
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemInfoGetTest() throws ApiException {
        Info response = api.systemInfoGet();

        // TODO: test validations
    }
    
    /**
     * Scale a function
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemScaleFunctionFunctionNamePostTest() throws ApiException {
        String functionName = null;
        byte[] input = null;
        api.systemScaleFunctionFunctionNamePost(functionName, input);

        // TODO: test validations
    }
    
}
